(() => {
  const D=window.RTBO_ACCESS_CENTER_DATA,$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  // Access is granted by a real super_admin role in the database (see
  // assets/super-admin-access.js + supabase/migrations/0001_shared_auth.sql),
  // never auto-enabled just by loading this page.
  let tab='pages';
  const state=()=>{const active=window.RTBOSuperAdminAccess?.isActive();$('#accessState').textContent=active?'ON':'OFF';$('#accessState').style.color=active?'#72e69b':'#ff7e76'};
  const platforms=[...new Set(D.pages.map(p=>p.platform))].sort();$('#platformFilter').innerHTML='<option value="">All platforms</option>'+platforms.map(p=>`<option>${esc(p)}</option>`).join('');
  function renderPages(){const q=$('#accessSearch').value.toLowerCase(),pf=$('#platformFilter').value;const rows=D.pages.filter(p=>(!pf||p.platform===pf)&&(!q||`${p.title} ${p.path} ${p.platform}`.toLowerCase().includes(q)));$('#pageCount').textContent=`${rows.length} of ${D.pages.length} project pages`;$('#pageGrid').innerHTML=rows.map(p=>`<a class="access-card" href="../${esc(p.path)}"><span>${esc(p.platform)}</span><strong>${esc(p.title||p.path)}</strong><small>${esc(p.path)}</small></a>`).join('')||'<div class="empty">No pages match the current search.</div>'}
  function renderCourses(){const q=$('#accessSearch').value.toLowerCase();const rows=D.tracks.filter(t=>!q||t.name.toLowerCase().includes(q)||'bachelor masters phd'.includes(q));$('#courseGrid').innerHTML=rows.map(t=>`<article class="course-card"><span class="eyebrow">${esc(t.name)}</span><h3>${esc(t.name)}</h3><div class="links">${D.pathways.map(p=>`<a href="../refzone-university/index.html#/course/${esc(t.id)}/${esc(p.id)}">${esc(p.name)}</a>`).join('')}</div></article>`).join('')||'<div class="empty">No courses match.</div>'}
  function renderMemberships(){const q=$('#accessSearch').value.toLowerCase();const rows=D.memberships.filter(m=>!q||m.name.toLowerCase().includes(q));$('#membershipGrid').innerHTML=rows.map(m=>`<article class="membership-admin-card"><span class="eyebrow">REFZONE MEMBERSHIP</span><h3>${esc(m.name)}</h3><p>Super Admin review access — no enrollment or payment required.</p><a href="../refzone-university/index.html#membership-access">Review membership →</a></article>`).join('')+`<article class="membership-admin-card"><span class="eyebrow">THE LIVE STREAM</span><h3>All Membership Levels</h3><a href="../live-stream/membership/index.html">Review plans →</a></article><article class="membership-admin-card"><span class="eyebrow">THE JAMMED UP BAR!</span><h3>All Membership Levels</h3><a href="../jammed-up-bar/subscribe/index.html#membership-plans">Review plans →</a></article>`}
  const features=[['Master CMS','cms/index.html'],['RTBO Super Admin Dashboard','SUPER_ADMIN_DASHBOARD.html'],['Got U Nex Ref Super Admin Profile','got-u-nex-ref/super-admin-profile/index.html'],['Got U Nex Ref Super Admin Dashboard','got-u-nex-ref/super-admin-dashboard/index.html'],['Got U Nex Ref Operational Dashboard','got-u-nex-ref/application/admin-dashboard.html'],['Got U Nex Ref Users','got-u-nex-ref/application/admin-users.html'],['Got U Nex Ref Assignments','got-u-nex-ref/application/admin-game-assignments.html'],['Got U Nex Ref Availability','got-u-nex-ref/application/admin-availability.html'],['Got U Nex Ref Payments','got-u-nex-ref/application/admin-payments.html'],['RefZone University Admin','refzone-university/index.html#/admin'],['RefZone University Student Dashboard','refzone-university/index.html#/dashboard'],['The Live Stream Account','live-stream/account/index.html'],['The Live Stream Membership','live-stream/membership/index.html'],['The Jammed Up Bar! Membership','jammed-up-bar/subscribe/index.html'],['The Vault Login Review','vault/login.html'],['The Vault Film Room','vault/film-room.html'],['The Cutting Room','cutting-room/index.html']];
  function renderFeatures(){const q=$('#accessSearch').value.toLowerCase();$('#featureGrid').innerHTML=features.filter(x=>!q||x[0].toLowerCase().includes(q)).map(x=>`<article class="feature-admin-card"><strong>${esc(x[0])}</strong><a href="../${esc(x[1])}">Open feature →</a></article>`).join('')||'<div class="empty">No features match.</div>'}
  function render(){state();({pages:renderPages,courses:renderCourses,memberships:renderMemberships,features:renderFeatures}[tab])()}
  $$('[data-tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;$$('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('[data-panel]').forEach(x=>x.classList.toggle('active',x.dataset.panel===tab));render()}));$('#accessSearch').addEventListener('input',render);$('#platformFilter').addEventListener('change',render);$('#enableAccess').addEventListener('click',()=>{window.RTBOSuperAdminAccess?.enable('all-access-center');render()});$('#disableAccess').addEventListener('click',()=>{window.RTBOSuperAdminAccess?.disable();render()});render();
})();