(() => {
"use strict";
const script=document.currentScript,pagePath=script?.dataset?.cmsPage||"",KEY="rtbo.masterCms.v1",preview=new URLSearchParams(location.search).get("cmsPreview")==="1",MEDIA_DB="rtbo.masterCms.media.v1",MEDIA_STORE="media";
function load(){try{return JSON.parse(localStorage.getItem(KEY)||"{}")||{}}catch{return{}}}
function merged(s){const p=s.published?.[pagePath]||{};if(!preview)return p;const d=s.drafts?.[pagePath]||{};return{...p,...d,meta:{...(p.meta||{}),...(d.meta||{})},elements:{...(p.elements||{}),...(d.elements||{})},insertions:[...(p.insertions||[]),...(d.insertions||[])]}}
function getMedia(id){return new Promise((res,rej)=>{const r=indexedDB.open(MEDIA_DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(MEDIA_STORE,{keyPath:"id"});r.onerror=()=>rej(r.error);r.onsuccess=()=>{const q=r.result.transaction(MEDIA_STORE).objectStore(MEDIA_STORE).get(id);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)}})}
async function media(v){if(typeof v!=="string"||!v.startsWith("cms-media://"))return v;const r=await getMedia(v.slice(12));return r?.dataUrl||v}
async function apply(){const s=load(),g=s.global||{};Object.entries(g.cssVars||{}).forEach(([k,v])=>document.documentElement.style.setProperty(k,String(v)));if(g.customCss){const st=document.createElement("style");st.textContent=g.customCss;document.head.appendChild(st)}const p=merged(s);if(p.meta?.title)document.title=p.meta.title;if(p.meta?.description!==undefined){let m=document.querySelector('meta[name="description"]');if(!m){m=document.createElement("meta");m.name="description";document.head.appendChild(m)}m.content=p.meta.description||""}if(p.customCss){const st=document.createElement("style");st.textContent=p.customCss;document.head.appendChild(st)}if(p.disabled){const d=document.createElement("div");d.style.cssText="position:fixed;z-index:2147483647;inset:0;display:grid;place-items:center;background:#030405;color:#fff;font-family:Arial;padding:30px;text-align:center";d.innerHTML='<div><strong style="display:block;color:#f45a0a;font-size:13px;letter-spacing:.15em">RAISING THE BAR OFFICIATING</strong><h1 style="font-size:40px">Page Unavailable</h1><p style="color:#aaa">This page has been disabled in the Master CMS.</p></div>';document.body.appendChild(d);return}for(const i of p.insertions||[]){try{const t=document.querySelector(i.target||"main")||document.body;if(i.enabled!==false)t.insertAdjacentHTML(i.position||"beforeend",i.html||"")}catch{}}for(const [sel,patch] of Object.entries(p.elements||{})){let e;try{e=document.querySelector(sel)}catch{continue}if(!e)continue;if(patch.removed){e.remove();continue}if(patch.hidden!==undefined)e.hidden=!!patch.hidden;if(patch.html!==undefined&&patch.html!==null)e.innerHTML=patch.html;else if(patch.text!==undefined&&patch.text!==null)e.textContent=patch.text;for(const [n,v] of Object.entries(patch.attrs||{})){const val=(n==="src"||n==="href")?await media(v):v;if(val===null||val===undefined||val==="")e.removeAttribute(n);else e.setAttribute(n,String(val))}}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",apply,{once:true});else apply();
})();