(()=>{'use strict';const $=(s,r=document)=>r.querySelector(s);const p=new URLSearchParams(location.search);const key=p.get('module')||'reports';if(key==='payments'){location.replace('admin-payments.html');return;}const map={
  schools:{title:'Schools & Teams',subtitle:'Manage school, team, organization, and venue records.',src:'modules/schools/index.html?embedded=1&route=schools&sub=directory#schools',nav:'schools'},
  'add-school-team':{title:'Add School / Team',subtitle:'Create home and visiting school/team records and contacts.',src:'modules/schools/index.html?embedded=1&route=schools&sub=add-teams#schools',nav:'schools'},
  'school-contacts':{title:'School / Team Contacts',subtitle:'Manage contacts connected to saved schools and teams.',src:'modules/schools/index.html?embedded=1&route=schools&sub=contacts#schools',nav:'schools'},
  availability:{title:'Availability',subtitle:'Review official availability and unavailability before assigning games.',src:'availability-report.html',nav:'availability'},
  payments:{title:'Payments',subtitle:'Review, record, and manage actual payment activity for assignments and officials.',src:'modules/game-report/index.html?embedded=1&route=payments#payments',nav:'payments'},
  'tax-center':{title:'Tax Center',subtitle:'Complete, sign, save, print, and manage official tax forms and tax documents.',src:'modules/game-report/index.html?embedded=1&route=tax-center#tax-center',nav:'tax-center'},
  'game-reports':{title:'Basketball Game Reports',subtitle:'Complete and review post-game basketball reports.',src:'modules/game-report/index.html?embedded=1&route=games&sub=reports#games',nav:'reports'},
  'referee-evaluations':{title:'Basketball Referee Evaluations',subtitle:'Create, review, finalize, deliver, and manage crew evaluations with controlled comment visibility.',src:'modules/evaluation/index.html?embedded=1&route=games&sub=evaluation#games',nav:'reports'},
  resources:{title:'Resources',subtitle:'Manage administrative resources and documents.',src:'modules/game-report/index.html?embedded=1&route=resources#resources'},
  messages:{title:'Messages',subtitle:'Administrative communications and conversations.',src:'modules/game-report/index.html?embedded=1&route=messages#messages'},
  notifications:{title:'Notifications',subtitle:'Review platform notifications and alerts.',src:'notifications.html'},
  support:{title:'Support',subtitle:'Manage support requests and platform assistance.',src:'modules/game-report/index.html?embedded=1&route=support#support'}
};const cfg=map[key];if(key==='reports'){document.title='Reports — Got U Nex Ref Admin';$('#moduleTitle').textContent='Reports';$('#moduleSubtitle').textContent='Availability, game reporting, evaluations, and financial reporting';$('#moduleFrame').hidden=true;const r=$('#reportsOverview');r.hidden=false;r.innerHTML=`<h2>Admin Reports</h2><p>Open the reporting workflow you need. The attached report and evaluation modules are preserved as dedicated dashboard sections.</p><div class="report-card-grid"><a class="report-card" href="admin-module.html?module=availability"><strong>Availability Report</strong><span>Review available, unavailable, and pending officials before game assignments.</span><b>Open Report →</b></a><a class="report-card" href="admin-module.html?module=game-reports"><strong>Basketball Game Reports</strong><span>Complete post-game crew-chief reports tied to published games.</span><b>Open Game Reports →</b></a><a class="report-card" href="admin-module.html?module=referee-evaluations"><strong>Basketball Referee Evaluations</strong><span>Create, save, edit, download, and review official evaluations.</span><b>Open Evaluations →</b></a><a class="report-card" href="admin-incident-reports.html"><strong>Incident Reports</strong><span>Review incident reports submitted by officials after completed games.</span><b>Open Incident Reports →</b></a><a class="report-card" href="admin-invoice-generator.html?view=reports"><strong>Invoice Reports</strong><span>Review invoice, payment, and receivables reporting.</span><b>Open Invoice Reports →</b></a></div>`;$('#reportsNav')?.setAttribute('open','');return;}if(!cfg){location.replace('admin-dashboard.html');return;}document.title=`${cfg.title} — Got U Nex Ref Admin`;$('#moduleTitle').textContent=cfg.title;$('#moduleSubtitle').textContent=cfg.subtitle;$('#moduleFrame').src=cfg.src;if(cfg.nav==='schools')$('#schoolsNav')?.setAttribute('open','');if(cfg.nav==='reports')$('#reportsNav')?.setAttribute('open','');if(cfg.nav==='availability')$('#availabilityNavLink')?.classList.add('active');if(cfg.nav==='payments')$('#paymentsNavLink')?.classList.add('active');if(cfg.nav==='tax-center')$('#taxCenterNavLink')?.classList.add('active');})();