(()=>{
'use strict';
const ADMIN_KEY='gotUNexRef.adminDashboard.v1';
const ASSIGN_KEY='gotUNexRef.adminAssignments.v1';
const TBA_KEY='gotUNexRef.tbaGames.v1';
const PORTAL_KEY='gotUNexRef.officialPortal.v3';
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const clone=v=>JSON.parse(JSON.stringify(v));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]||c));
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||'null')||clone(fallback)}catch{return clone(fallback)}};
const save=(key,val)=>localStorage.setItem(key,JSON.stringify(val));

let admin=load(ADMIN_KEY,{users:[],notifications:[],messages:[],options:{},currentAdmin:{}});
let store=load(ASSIGN_KEY,{assignments:[],drafts:[]});
let tba=load(TBA_KEY,{games:[]});
let portal=load(PORTAL_KEY,{assignments:[]});
admin.users=Array.isArray(admin.users)?admin.users:[];
admin.notifications=Array.isArray(admin.notifications)?admin.notifications:[];
admin.messages=Array.isArray(admin.messages)?admin.messages:[];
store.assignments=Array.isArray(store.assignments)?store.assignments:[];
tba.games=Array.isArray(tba.games)?tba.games:[];
portal.assignments=Array.isArray(portal.assignments)?portal.assignments:[];

function cleanLegacyDemoData(){
  const cleanTba=tba.games.filter(g=>!/^tba-100[1-7]$/.test(String(g?.id||'')));
  if(cleanTba.length!==tba.games.length){tba.games=cleanTba;save(TBA_KEY,tba);}
  const cleanUsers=admin.users.filter(u=>!(/^u(?:10|[1-9])$/.test(String(u?.id||u?.userId||''))&&!u?.email&&!u?.username&&!u?.createdAt));
  if(cleanUsers.length!==admin.users.length){admin.users=cleanUsers;save(ADMIN_KEY,admin);}
}
cleanLegacyDemoData();

const state={page:1,perPage:10,tab:'games',search:'',sport:'',level:'',time:'',venue:'',crew:'',role:'',cert:'',radius:25,mode:'',preserve:'',sessionAssignments:0,sessionTimeSaved:0};
const modalState={gameId:null,selected:[],menu:''};
let toastTimer;

function toast(msg){const el=$('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function initials(name){return String(name||'').split(/\s+/).filter(Boolean).slice(0,2).map(v=>v[0]).join('').toUpperCase()||'?'}
function dateObj(date){const d=new Date(String(date||'')+'T12:00:00');return Number.isNaN(d.getTime())?null:d}
function dayLabel(date){const d=dateObj(date);if(!d)return'TBA';const today=new Date();today.setHours(12,0,0,0);const diff=Math.round((d-today)/86400000);if(diff===0)return'Today';if(diff===1)return'Tomorrow';return d.toLocaleDateString('en-US',{month:'short',day:'numeric'})}
function formatDate(date){const d=dateObj(date);return d?d.toLocaleDateString('en-US',{month:'short',day:'numeric'}):(date||'Not provided')}
function fullDate(date){const d=dateObj(date);return d?d.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'}):(date||'Not provided')}
function formatTime(time){const [h,m='00']=String(time||'').split(':');const hh=Number(h);return Number.isFinite(hh)?`${hh%12||12}:${String(m).padStart(2,'0')} ${hh>=12?'PM':'AM'}`:(time||'Not provided')}
function currentAdmin(){const c=admin.options?.currentAdmin||admin.currentAdmin||{};return{name:c.name||[c.firstName,c.lastName].filter(Boolean).join(' ')||'Administrator',role:c.role||c.title||'Administrator',photo:c.photo||c.profilePhoto||c.avatar||'assets/profile-placeholder.svg'}}
function renderTopbar(){const info=currentAdmin();$('#topUserName').textContent=info.name;$('#topUserRole').textContent=info.role;$('#topUserAvatar').src=info.photo;$('#topBellCount').textContent=admin.notifications.length||0;$('#sidebarNotificationCount').textContent=admin.notifications.length||0;$('#sidebarMessageCount').textContent=admin.messages.length||0}
function isOfficial(u){const role=String(u?.role||u?.roleLabel||u?.userType||'').toLowerCase();return role.includes('official')||['referee','umpire','alternate'].includes(role)}
function userId(u){return String(u?.officialId||u?.id||u?.userId||u?.email||'')}
function userName(u){return u?.name||[u?.firstName,u?.lastName].filter(Boolean).join(' ')||u?.email||u?.username||'Official'}
function normalizedSports(u){const raw=u?.sports||u?.sport||u?.preferredSports||[];return (Array.isArray(raw)?raw:[raw]).filter(Boolean).map(String)}
function normalizedCerts(u){const raw=u?.certifications||u?.certification||u?.classification||u?.preferredLevel||u?.level||[];return (Array.isArray(raw)?raw:[raw]).filter(Boolean).map(String)}
function normalizedDistance(u){const v=u?.distance??u?.distanceMiles??u?.locationRadius??u?.travelDistance;const n=Number(v);return Number.isFinite(n)?n:null}
function allUsers(){return admin.users.filter(isOfficial).map(u=>({id:userId(u),name:userName(u),role:u.officialType||u.position||u.assignmentPosition||u.roleLabel||u.role||'Official',sports:normalizedSports(u),certifications:normalizedCerts(u),distance:normalizedDistance(u),city:u.location||[u.city||u.address?.city,u.state||u.address?.state].filter(Boolean).join(', '),raw:u})).filter(u=>u.id)}
function statusAtDate(u,date){const explicit=u?.raw?.availability?.byDate?.[date];if(explicit)return explicit;const blocks=u?.raw?.availability?.blocksByDate?.[date];const block=Array.isArray(blocks)?blocks[0]:blocks;if(block?.fullDay)return'unavailable';if(block)return'partial';return''}
function portalAcceptedIds(adminAssignmentId){return portal.assignments.filter(a=>String(a.adminAssignmentId||a.assignmentId||'')===String(adminAssignmentId)&&String(a.status||a.workflowStatus||'').toLowerCase()==='accepted').map(a=>String(a.officialId||a.assigneeId||'')).filter(Boolean)}
function acceptedIdsFromRecord(r){
  const ids=new Set([...(r.acceptedOfficialIds||[]),...(r.previousAcceptedOfficialIds||[]),...(r.returningOfficials||[])] .map(String));
  (r.crew||[]).forEach(m=>{const status=String(m.status||m.response||m.workflowStatus||'').toLowerCase();if(m.accepted===true||status==='accepted')ids.add(String(m.officialId||m.id||''));});
  portalAcceptedIds(r.id).forEach(id=>ids.add(id));
  ids.delete('');return [...ids];
}
function primaryCrewIds(r){return (r.crew||[]).filter(m=>!String(m.role||'').toLowerCase().includes('alternate')&&!String(m.role||'').toLowerCase().includes('training')).map(m=>String(m.officialId||m.id||'')).filter(Boolean)}
function assignmentToGame(r){
  const returning=acceptedIdsFromRecord(r);const crewNeeded=Number(r.crewSize||r.officialsNeeded||2)||2;const primary=primaryCrewIds(r);
  const trainingCount=Array.isArray(r.trainingAssignments)?r.trainingAssignments.length:Number(r.trainingRecommended||r.trainingSlots||0)||0;
  return{id:`assignment:${r.id}`,sourceAssignmentId:String(r.id),source:'assignment',date:r.date||r.gameDate||'',time:r.time||r.startTime||'',homeTeam:r.homeTeam||r.homeSchool||'Not provided',awayTeam:r.visitingTeam||r.awayTeam||r.visitingSchool||'Not provided',homeMark:initials(r.homeTeam||r.homeSchool||'H').charAt(0),awayMark:initials(r.visitingTeam||r.awayTeam||r.visitingSchool||'A').charAt(0),homeColor:'#a31a15',awayColor:'#375f9b',sport:r.sport||'',level:r.level||'',venue:r.venue||r.location||'Not provided',location:r.address||r.venueAddress||'',crewNeeded,assigned:primary.length,distance:Number.isFinite(Number(r.distance||r.distanceMiles))?Number(r.distance||r.distanceMiles):null,mode:returning.length?'returning':trainingCount?'training':'new',returningOfficials:returning,trainingRecommended:trainingCount,notes:r.notes||'',original:r}
}
function tbaToGame(r){return{id:`tba:${r.id}`,sourceTbaId:String(r.id),source:'tba',date:r.date||'',time:r.time||'',homeTeam:r.homeTeam||'Not provided',awayTeam:r.awayTeam||r.visitingTeam||'Not provided',homeMark:r.homeMark||initials(r.homeTeam||'H').charAt(0),awayMark:r.awayMark||initials(r.awayTeam||r.visitingTeam||'A').charAt(0),homeColor:r.homeColor||'#a31a15',awayColor:r.awayColor||'#375f9b',sport:r.sport||'',level:r.level||'',venue:r.venue||'Not provided',location:r.location||r.address||'',crewNeeded:Number(r.crewNeeded||r.crewSize||2)||2,assigned:Number(r.assigned||0)||0,distance:Number.isFinite(Number(r.distance))?Number(r.distance):null,mode:'new',returningOfficials:[],trainingRecommended:Number(r.trainingRecommended||0)||0,notes:r.notes||'',original:r}}
function games(){
  const map=new Map();
  store.assignments.map(assignmentToGame).forEach(g=>map.set(`${g.date}|${g.time}|${g.homeTeam}|${g.awayTeam}`,g));
  tba.games.map(tbaToGame).forEach(g=>{const key=`${g.date}|${g.time}|${g.homeTeam}|${g.awayTeam}`;if(!map.has(key))map.set(key,g)});
  return [...map.values()].sort((a,b)=>`${a.date||''}T${a.time||''}`.localeCompare(`${b.date||''}T${b.time||''}`));
}
function gameById(id){return games().find(g=>g.id===id)}
function teamBadge(mark,color){return `<span class="team-badge" style="background:${esc(color)}">${esc(mark)}</span>`}
function modeLabel(mode){return mode==='returning'?'Returning Crew':mode==='training'?'Training Assignment':'New Assignment'}
function statusPill(mode){return `<span class="status-pill ${esc(mode)}">${esc(modeLabel(mode))}</span>`}
function availabilityOkay(user,game){if(game.returningOfficials.includes(user.id))return true;const status=statusAtDate(user,game.date);return status!=='unavailable'}
function sportMatches(user,game){if(!game.sport||!user.sports.length)return true;return user.sports.some(s=>s.toLowerCase()===String(game.sport).toLowerCase())}
function certificationMatches(user,game){if(!game.level||!user.certifications.length)return true;const level=String(game.level).toLowerCase();return user.certifications.some(c=>level.includes(String(c).toLowerCase())||String(c).toLowerCase().includes(level))}
function matchedOfficials(game){
  return allUsers().filter(u=>availabilityOkay(u,game)).filter(u=>!state.role||String(u.role).toLowerCase().includes(state.role.toLowerCase())).filter(u=>!state.cert||u.certifications.includes(state.cert)).filter(u=>u.distance===null||u.distance<=Number(state.radius||25)).map(u=>{
    const returning=game.returningOfficials.includes(u.id);let score=3;
    if(returning)score+=1.2;if(sportMatches(u,game))score+=.4;if(certificationMatches(u,game))score+=.3;if(u.distance!==null&&u.distance<=Number(state.radius||25))score+=.1;
    score=Math.max(1,Math.min(5,score));return{...u,returning,score};
  }).sort((a,b)=>b.score-a.score || (a.distance??9999)-(b.distance??9999));
}
function suggestedCrew(game){
  const matches=matchedOfficials(game),primary=[],training=[],used=new Set();
  game.returningOfficials.forEach(id=>{const u=matches.find(m=>m.id===id);if(u&&primary.length<game.crewNeeded){primary.push({...u,slot:'Primary'});used.add(u.id)}});
  matches.forEach(u=>{if(primary.length<game.crewNeeded&&!used.has(u.id)){primary.push({...u,slot:'Primary'});used.add(u.id)}});
  matches.forEach(u=>{if(training.length<game.trainingRecommended&&!used.has(u.id)){training.push({...u,slot:'Training'});used.add(u.id)}});
  const score=primary.length?primary.reduce((a,b)=>a+b.score,0)/primary.length:0;return{primary,training,score};
}
function filteredGames(){
  let list=games();if(state.search){const q=state.search.toLowerCase();list=list.filter(g=>[g.id,g.homeTeam,g.awayTeam,g.venue,g.location,g.sport,g.level].join(' ').toLowerCase().includes(q))}if(state.sport)list=list.filter(g=>g.sport===state.sport);if(state.level)list=list.filter(g=>g.level===state.level);if(state.venue)list=list.filter(g=>g.venue===state.venue);if(state.crew)list=list.filter(g=>String(g.crewNeeded)===String(state.crew));if(state.mode)list=list.filter(g=>g.mode===state.mode);if(state.preserve==='yes')list=list.filter(g=>g.returningOfficials.length);if(state.preserve==='no')list=list.filter(g=>!g.returningOfficials.length);if(state.time==='day')list=list.filter(g=>Number(String(g.time||'0').split(':')[0])<17);if(state.time==='evening')list=list.filter(g=>Number(String(g.time||'0').split(':')[0])>=17);return list;
}
function renderFilters(){const list=games();const sports=[...new Set(list.map(g=>g.sport).filter(Boolean))].sort();const levels=[...new Set(list.map(g=>g.level).filter(Boolean))].sort();const venues=[...new Set(list.map(g=>g.venue).filter(v=>v&&v!=='Not provided'))].sort();const certs=[...new Set(allUsers().flatMap(u=>u.certifications).filter(Boolean))].sort();$('#sportFilter').innerHTML='<option value="">All Sports</option>'+sports.map(v=>`<option ${state.sport===v?'selected':''}>${esc(v)}</option>`).join('');$('#levelFilter').innerHTML='<option value="">All Levels</option>'+levels.map(v=>`<option ${state.level===v?'selected':''}>${esc(v)}</option>`).join('');$('#venueFilter').innerHTML='<option value="">All Venues</option>'+venues.map(v=>`<option ${state.venue===v?'selected':''}>${esc(v)}</option>`).join('');$('#certFilter').innerHTML='<option value="">All Certifications</option>'+certs.map(v=>`<option ${state.cert===v?'selected':''}>${esc(v)}</option>`).join('');$('#timeFilter').value=state.time;$('#crewNeededFilter').value=state.crew;$('#roleFilter').value=state.role;$('#radiusFilter').value=String(state.radius);$('#assignmentModeFilter').value=state.mode;$('#preserveFilter').value=state.preserve}
function renderStats(){const list=filteredGames();$('#statGames').textContent=list.length;const avail=allUsers().filter(u=>u.distance===null||u.distance<=Number(state.radius||25)).filter(u=>!state.cert||u.certifications.includes(state.cert)).filter(u=>!state.role||String(u.role).toLowerCase().includes(state.role.toLowerCase())).length;$('#statOfficials').textContent=avail;$('#statAssignments').textContent=state.sessionAssignments;const mins=Math.floor(state.sessionTimeSaved/60),secs=String(state.sessionTimeSaved%60).padStart(2,'0');$('#statTimeSaved').textContent=`${mins}m ${secs}s`;$('#countGames').textContent=list.length;$('#countMatched').textContent=list.reduce((n,g)=>n+matchedOfficials(g).length,0);$('#countSuggested').textContent=list.length}
function starMarkup(score){const filled=Math.round(score);let out='';for(let i=1;i<=5;i++)out+=`<svg style="opacity:${i<=filled?1:.25}" viewBox="0 0 24 24"><use href="#i-star"/></svg>`;const cls=score>=4.5?'':score>=3.5?'good':'fair';return `<div class="stars ${cls}">${out}</div>`}
function actionMenu(id){return `<div class="actions"><div class="combo-btn"><button type="button" data-open-assign="${esc(id)}"><svg><use href="#i-personadd"/></svg>Quick Assign</button><button type="button" data-toggle-menu="${esc(id)}"><svg><use href="#i-chevron"/></svg></button></div><div class="menu-wrap"><div class="row-menu ${modalState.menu===id?'open':''}" data-menu="${esc(id)}"><button type="button" data-row-action="open" data-id="${esc(id)}">Open quick assign</button><button type="button" data-row-action="builder" data-id="${esc(id)}">Open assignment builder</button><button type="button" data-row-action="auto" data-id="${esc(id)}">Apply suggested crew</button></div></div></div>`}
function rowGames(game){const s=suggestedCrew(game),quality=s.score,label=quality>=4.5?'Excellent':quality>=3.5?'Good':quality?'Fair':'No matches';return `<tr><td><div class="date-cell"><span class="date-bar ${dayLabel(game.date)==='Today'?'today':dayLabel(game.date)==='Tomorrow'?'tomorrow':''}"></span><div class="date-copy"><strong>${esc(dayLabel(game.date))}</strong><span>${esc(formatDate(game.date))}</span><span>${esc(formatTime(game.time))}</span></div></div></td><td><div class="game-cell">${teamBadge(game.homeMark,game.homeColor)}<div class="team-copy"><strong>${esc(game.homeTeam)}</strong></div><span class="versus">vs</span>${teamBadge(game.awayMark,game.awayColor)}<div class="team-copy"><strong>${esc(game.awayTeam)}</strong></div></div></td><td><div class="sport-copy"><strong>${esc(game.sport||'Not provided')}</strong><span>${esc(game.level||'Not provided')}</span></div></td><td><div class="venue-copy"><strong>${esc(game.venue||'Not provided')}</strong><span>${esc(game.location||'')}</span></div></td><td><div class="crew-copy"><strong>${game.crewNeeded} Officials</strong><span>${s.primary.length} matched now</span></div></td><td><div class="distance-copy">${game.distance===null?'Not provided':`${game.distance.toFixed(1)} mi`}</div></td><td><div class="quality">${starMarkup(quality)}<span>${esc(label)}</span></div></td><td>${actionMenu(game.id)}</td></tr>`}
function rowMatches(game){const matches=matchedOfficials(game).slice(0,8),ret=matches.filter(m=>m.returning).length,best=matches.find(m=>m.distance!==null);return `<tr><td><div class="venue-copy"><strong>${esc(game.homeTeam)} vs ${esc(game.awayTeam)}</strong><span>${esc(formatDate(game.date))} • ${esc(game.sport||'Sport not provided')} • ${esc(game.level||'Level not provided')}</span></div></td><td>${matches.length?matches.map(m=>`<span class="official-pill"><span class="avatar">${esc(initials(m.name))}</span>${esc(m.name)}</span>`).join(''):'<span class="muted">No matching officials</span>'}</td><td>${statusPill(ret?'returning':'new')}<div class="muted">${ret} returning official(s)</div></td><td><div class="crew-copy"><strong>${matches.filter(m=>certificationMatches(m,game)).length}</strong><span>certified matches</span></div></td><td><div class="distance-copy">${best?`${best.distance.toFixed(1)} mi`:'Not provided'}</div></td><td>${actionMenu(game.id)}</td></tr>`}
function rowSuggested(game){const s=suggestedCrew(game);return `<tr><td><div class="venue-copy"><strong>${esc(game.homeTeam)} vs ${esc(game.awayTeam)}</strong><span>${esc(formatDate(game.date))} • ${esc(formatTime(game.time))}</span></div></td><td>${s.primary.length?s.primary.map(m=>`<span class="official-pill"><span class="avatar">${esc(initials(m.name))}</span>${esc(m.name)}</span>`).join(''):'<span class="muted">No suggested crew</span>'}</td><td>${statusPill(game.mode)}</td><td><div class="crew-copy"><strong>${s.training.length}</strong><span>additional official(s)</span></div></td><td><div class="crew-copy"><strong>${game.returningOfficials.length?'Enabled':'Not Needed'}</strong><span>${game.returningOfficials.length?'Returning accepted officials retain acceptance':'New assignment workflow'}</span></div></td><td>${actionMenu(game.id)}</td></tr>`}
function renderTable(){const list=filteredGames(),pages=Math.max(1,Math.ceil(list.length/state.perPage));if(state.page>pages)state.page=pages;const start=(state.page-1)*state.perPage,slice=list.slice(start,start+state.perPage);let headers,rowFn;if(state.tab==='games'){headers=['Date & Time','Game','Sport / Level','Venue','Crew Needed','Distance','Match Quality','Actions'];rowFn=rowGames}else if(state.tab==='matches'){headers=['Game','Matched Officials','Returning Crew','Certification Match','Best Distance','Actions'];rowFn=rowMatches}else{headers=['Game','Suggested Crew','Mode','Training Extras','Auto Reaccept','Actions'];rowFn=rowSuggested}$('#tableHead').innerHTML=`<tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr>`;$('#tableBody').innerHTML=slice.map(rowFn).join('');$('#emptyState').hidden=!!slice.length;$('#tableSummary').textContent=list.length?`Showing ${start+1} to ${Math.min(start+state.perPage,list.length)} of ${list.length} ${state.tab==='matches'?'matches':'games'}`:`Showing 0 ${state.tab==='matches'?'matches':'games'}`;$('#pageIndicator').textContent=state.page;$('#firstPageBtn').disabled=state.page<=1;$('#prevPageBtn').disabled=state.page<=1;$('#nextPageBtn').disabled=state.page>=pages;$('#lastPageBtn').disabled=state.page>=pages}
function openAssignModal(id){const game=gameById(id);if(!game)return;modalState.gameId=id;const s=suggestedCrew(game);modalState.selected=[...s.primary.map(u=>({id:u.id,name:u.name,role:u.role,slot:'Primary'})),...s.training.map(u=>({id:u.id,name:u.name,role:u.role,slot:'Training'}))];$('#modalGameTitle').textContent=`${game.homeTeam} vs ${game.awayTeam}`;$('#modalGameMeta').textContent=`${fullDate(game.date)} • ${formatTime(game.time)} • ${game.sport||'Sport not provided'} / ${game.level||'Level not provided'}`;$('#modalGameVenue').textContent=`${game.venue||'Venue not provided'}${game.location?` • ${game.location}`:''}`;$('#modalAssignmentMode').value=game.mode;$('#modalCrewNeeded').value=String(game.crewNeeded);$('#modalTrainingExtras').value=String(game.trainingRecommended||0);$('#modalPreserve').value=game.returningOfficials.length?'yes':'no';$('#returningBanner').style.display=game.returningOfficials.length?'block':'none';$('#assignModal').hidden=false;renderModalLists()}
function closeAssignModal(){$('#assignModal').hidden=true;modalState.gameId=null}
function renderModalLists(){const game=gameById(modalState.gameId);if(!game)return;const matches=matchedOfficials(game).slice(0,12);$('#suggestedOfficialsList').innerHTML=matches.length?matches.map(u=>`<div class="interest-row"><div class="interest-person"><span class="interest-avatar">${esc(initials(u.name))}</span><div class="interest-copy"><strong>${esc(u.name)}</strong><span>${esc(u.role)}${u.city?` • ${esc(u.city)}`:''}${u.certifications.length?` • ${esc(u.certifications.join(', '))}`:''}</span></div></div><div class="interest-actions"><span class="pill ${u.returning?'green':'orange'}">${u.returning?'Returning':'Suggested'}</span><button class="assign-btn" type="button" data-pick-user="${esc(u.id)}">${modalState.selected.some(s=>s.id===u.id)?'Selected':'Select'}</button></div></div>`).join(''):'<div class="table-empty">No available officials match this game and the current filters.</div>';$('#selectedCrewList').innerHTML=modalState.selected.length?modalState.selected.map(u=>`<div class="selected-row"><div class="meta"><strong>${esc(u.name)}</strong><span>${esc(u.role)} • ${u.slot==='Training'?'Training official':'Primary crew'}</span></div><span class="tag ${u.slot==='Training'?'training':'primary'}">${u.slot}</span><button class="remove-mini" type="button" data-remove-user="${esc(u.id)}">×</button></div>`).join(''):'<div class="table-empty">No officials selected yet.</div>'}
function pickUser(id){const game=gameById(modalState.gameId);if(!game||modalState.selected.some(s=>s.id===id))return;const u=matchedOfficials(game).find(x=>x.id===id);if(!u)return;const primaryLimit=Number($('#modalCrewNeeded').value||game.crewNeeded),trainingLimit=Number($('#modalTrainingExtras').value||0),primaryCount=modalState.selected.filter(s=>s.slot==='Primary').length,trainingCount=modalState.selected.filter(s=>s.slot==='Training').length;const slot=primaryCount<primaryLimit?'Primary':trainingCount<trainingLimit?'Training':'';if(!slot){toast('Selected crew and training slots are full.');return}modalState.selected.push({id:u.id,name:u.name,role:u.role,slot});renderModalLists()}
function removeUser(id){modalState.selected=modalState.selected.filter(u=>u.id!==id);renderModalLists()}
function notifyAssignment(game,record){const targets=[...new Set(record.crew.map(c=>c.officialId).filter(Boolean))];if(!targets.length)return;admin.notifications.unshift({id:`notif-${Date.now()}`,title:'Game assignment update',message:`${game.homeTeam} vs ${game.awayTeam} was updated through Quick Assign.${record.autoAcceptedReturningOfficials?' Returning accepted officials remain accepted and do not need to reaccept.':''}`,targets,createdAt:new Date().toISOString()});admin.messages.unshift({id:`msg-${Date.now()}`,subject:'Game assignment update',body:`${game.homeTeam} vs ${game.awayTeam} has been updated.${record.autoAcceptedReturningOfficials?' Your prior acceptance remains in effect.':''}`,targets,createdAt:new Date().toISOString()});save(ADMIN_KEY,admin)}
function buildRecord(game,selected,opts){const primary=selected.filter(s=>s.slot==='Primary').slice(0,opts.crewNeeded),training=selected.filter(s=>s.slot==='Training');const base=game.original&&game.source==='assignment'?clone(game.original):{};const existingById=new Map((base.crew||[]).map(m=>[String(m.officialId||''),m]));const primaryCrew=primary.map((p,idx)=>{const prior=existingById.get(p.id)||{};const returning=opts.preserve&&game.returningOfficials.includes(p.id);return{...prior,role:prior.role||(idx===0?'Referee':`Umpire ${idx}`),officialId:p.id,name:p.name,position:p.role,status:returning?'accepted':'assigned',accepted:returning}});const trainingCrew=training.map((p,idx)=>({role:`Training ${idx+1}`,officialId:p.id,name:p.name,position:p.role,status:'training',accepted:false,training:true}));return{...base,id:game.sourceAssignmentId||base.id||`quick-${crypto.randomUUID?.()||Date.now()}`,assignmentType:base.assignmentType||'game',title:`${game.homeTeam} vs ${game.awayTeam}`,matchup:`${game.homeTeam} vs ${game.awayTeam}`,sport:game.sport,level:game.level,date:game.date,time:game.time,venue:game.venue,location:game.location,homeTeam:game.homeTeam,awayTeam:game.awayTeam,visitingTeam:game.awayTeam,crewSize:opts.crewNeeded,status:base.status||'pending',workflowStatus:base.workflowStatus||base.status||'pending',published:base.published??true,quickAssignMode:opts.mode,preserveAcceptedOfficials:opts.preserve,autoAcceptedReturningOfficials:opts.preserve&&game.returningOfficials.length>0&&opts.autoAccept,trainingAssignments:training.map(t=>t.id),officialIds:primary.map(p=>p.id),crew:[...primaryCrew,...trainingCrew],updatedAt:new Date().toISOString(),quickAssignedAt:new Date().toISOString()}}
function persistRecord(record){const idx=store.assignments.findIndex(r=>String(r.id)===String(record.id));if(idx>=0)store.assignments[idx]=record;else store.assignments.unshift(record);save(ASSIGN_KEY,store);portal=load(PORTAL_KEY,{assignments:[]});portal.assignments=Array.isArray(portal.assignments)?portal.assignments:[];record.crew.filter(c=>!c.training).forEach(c=>{const pid=`${record.id}:${c.officialId}`;const old=portal.assignments.find(a=>a.id===pid||String(a.adminAssignmentId)===String(record.id)&&String(a.officialId||a.assigneeId)===String(c.officialId));const returning=c.accepted===true;const next={...(old||{}),...record,id:pid,adminAssignmentId:record.id,officialId:c.officialId,assigneeId:c.officialId,position:c.role,status:returning?'accepted':'pending',workflowStatus:returning?'accepted':'pending',respondedAt:returning?(old?.respondedAt||new Date().toISOString()):old?.respondedAt};const oi=portal.assignments.findIndex(a=>a.id===pid);if(oi>=0)portal.assignments[oi]=next;else portal.assignments.unshift(next)});save(PORTAL_KEY,portal)}
function applyAssignment(gameId=modalState.gameId,openBuilder=false,customSelected=null,customOpts=null){const game=gameById(gameId);if(!game)return;const s=customSelected||modalState.selected;const opts=customOpts||{crewNeeded:Number($('#modalCrewNeeded')?.value||game.crewNeeded||2),mode:$('#modalAssignmentMode')?.value||game.mode||'new',preserve:($('#modalPreserve')?.value||'yes')==='yes',autoAccept:$('#autoAcceptCheck')?.checked??true};if(s.filter(x=>x.slot==='Primary').length<opts.crewNeeded){toast(`At least ${opts.crewNeeded} matching officials are required.`);return}const record=buildRecord(game,s,opts);persistRecord(record);if($('#notifyAssignedCheck')?.checked??true)notifyAssignment(game,record);state.sessionAssignments++;state.sessionTimeSaved+=34;renderTopbar();renderStats();renderTable();toast(openBuilder?'Assignment saved. Opening assignment builder…':'Quick assignment applied.');closeAssignModal();if(openBuilder){sessionStorage.setItem('gotUNexRef.editAssignmentId',record.id);setTimeout(()=>location.href=`admin-create-assignment.html?crew=${opts.crewNeeded}&edit=${encodeURIComponent(record.id)}`,350)}}
function bulkAutoAssign(){const list=filteredGames();if(!list.length){toast('No games are available to auto assign.');return}let applied=0;list.forEach(game=>{const s=suggestedCrew(game);if(s.primary.length<game.crewNeeded)return;const selected=[...s.primary.map(u=>({id:u.id,name:u.name,role:u.role,slot:'Primary'})),...s.training.map(u=>({id:u.id,name:u.name,role:u.role,slot:'Training'}))];const opts={crewNeeded:game.crewNeeded,mode:game.mode,preserve:game.returningOfficials.length>0,autoAccept:true};const record=buildRecord(game,selected,opts);persistRecord(record);notifyAssignment(game,record);applied++});state.sessionAssignments+=applied;state.sessionTimeSaved+=applied*34;renderTopbar();renderStats();renderTable();toast(applied?`${applied} game(s) auto-assigned.`:'No games had enough matching officials to auto assign.')}
function bind(){
 [['sportFilter','sport'],['levelFilter','level'],['timeFilter','time'],['venueFilter','venue'],['crewNeededFilter','crew'],['roleFilter','role'],['certFilter','cert'],['assignmentModeFilter','mode'],['preserveFilter','preserve']].forEach(([id,key])=>$('#'+id).addEventListener('change',e=>{state[key]=e.target.value;state.page=1;renderStats();renderTable()}));$('#radiusFilter').addEventListener('change',e=>{state.radius=Number(e.target.value||25);state.page=1;renderStats();renderTable()});$('#searchInput').addEventListener('input',e=>{state.search=e.target.value.trim();state.page=1;renderTable()});$('#toggleFiltersBtn').addEventListener('click',()=>{$('#advancedFilters').hidden=!$('#advancedFilters').hidden});$('#useLocationBtn').addEventListener('click',()=>{toast('Location radius is ready. Connect browser geolocation or an admin location service to calculate live travel distance.')});$('#autoAssignBtn').addEventListener('click',bulkAutoAssign);$('#clearAllBtn').addEventListener('click',()=>{Object.assign(state,{page:1,search:'',sport:'',level:'',time:'',venue:'',crew:'',role:'',cert:'',radius:25,mode:'',preserve:''});$('#searchInput').value='';renderFilters();renderStats();renderTable()});$('#refreshBtn').addEventListener('click',()=>{admin=load(ADMIN_KEY,admin);store=load(ASSIGN_KEY,store);tba=load(TBA_KEY,tba);portal=load(PORTAL_KEY,portal);renderFilters();renderStats();renderTable();toast('Quick Assign refreshed from current dashboard data.')});$('#perPageSelect').addEventListener('change',e=>{state.perPage=Number(e.target.value||10);state.page=1;renderTable()});$('#firstPageBtn').addEventListener('click',()=>{state.page=1;renderTable()});$('#prevPageBtn').addEventListener('click',()=>{if(state.page>1){state.page--;renderTable()}});$('#nextPageBtn').addEventListener('click',()=>{const max=Math.max(1,Math.ceil(filteredGames().length/state.perPage));if(state.page<max){state.page++;renderTable()}});$('#lastPageBtn').addEventListener('click',()=>{state.page=Math.max(1,Math.ceil(filteredGames().length/state.perPage));renderTable()});$$('#tabRow .tab').forEach(btn=>btn.addEventListener('click',()=>{$$('#tabRow .tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.tab=btn.dataset.tab;state.page=1;renderTable()}));
 document.addEventListener('click',e=>{const open=e.target.closest('[data-open-assign]'),toggle=e.target.closest('[data-toggle-menu]'),action=e.target.closest('[data-row-action]'),close=e.target.closest('[data-close-modal]'),pick=e.target.closest('[data-pick-user]'),remove=e.target.closest('[data-remove-user]');if(open){openAssignModal(open.dataset.openAssign);return}if(toggle){modalState.menu=modalState.menu===toggle.dataset.toggleMenu?'':toggle.dataset.toggleMenu;renderTable();return}if(action){const id=action.dataset.id,a=action.dataset.rowAction;modalState.menu='';renderTable();if(a==='open')openAssignModal(id);else if(a==='builder'){openAssignModal(id);setTimeout(()=>$('#openBuilderBtn').click(),20)}else if(a==='auto'){const g=gameById(id),s=suggestedCrew(g);const selected=[...s.primary.map(u=>({id:u.id,name:u.name,role:u.role,slot:'Primary'})),...s.training.map(u=>({id:u.id,name:u.name,role:u.role,slot:'Training'}))];applyAssignment(id,false,selected,{crewNeeded:g.crewNeeded,mode:g.mode,preserve:g.returningOfficials.length>0,autoAccept:true})}return}if(close){closeAssignModal();return}if(pick){pickUser(pick.dataset.pickUser);return}if(remove){removeUser(remove.dataset.removeUser);return}if(!e.target.closest('.combo-btn')&&!e.target.closest('.row-menu')){modalState.menu='';renderTable()}});
 $('#modalCrewNeeded').addEventListener('change',renderModalLists);$('#modalTrainingExtras').addEventListener('change',renderModalLists);$('#openBuilderBtn').addEventListener('click',()=>applyAssignment(modalState.gameId,true));$('#saveAssignmentBtn').addEventListener('click',()=>applyAssignment(modalState.gameId,false));document.addEventListener('keydown',e=>{if(e.key==='Escape'){modalState.menu='';renderTable();closeAssignModal()}})
}
renderTopbar();renderFilters();renderStats();renderTable();bind();
})();
